# -*- coding: utf-8 -*-
"""GENERAL PURPOSE BASE LLM

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tia_jiDe9a9A9Bavl2jh3BBtwbKZX0D9
"""

!pip install -q transformers accelerate torch sentencepiece

import torch
import random
import numpy as np

SEED = 42
torch.manual_seed(SEED)
np.random.seed(SEED)
random.seed(SEED)

"""Load Phi-2"""

from transformers import AutoTokenizer, AutoModelForCausalLM, AutoConfig
import torch

model_name = "microsoft/phi-2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
config = AutoConfig.from_pretrained(model_name)
config.pad_token_id = tokenizer.eos_token_id
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    config=config,
    dtype=torch.float16,
    device_map="auto"
)

model.eval()

GEN_CONFIG = {
    "max_new_tokens": 150,
    "temperature": 0.7,
    "top_p": 0.9,
    "do_sample": True,
    "pad_token_id": tokenizer.eos_token_id,
    "eos_token_id": tokenizer.eos_token_id
}

"""MODEL BASELINE TESTING"""

prompt = "Explain artificial intelligence in one paragraph."

inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

with torch.no_grad():
    outputs = model.generate(
        **inputs,
        max_new_tokens=100,
        do_sample=True,
        temperature=0.7
    )

print(tokenizer.decode(outputs[0], skip_special_tokens=True))

"""TASK 1-Risk Explanation"""

risk_prompt = """
You are a legal assistant. Review the following contract and identify any clauses that may pose legal or financial risk to a party. Explain your reasoning clearly.

Contract:
{contract_text}
"""

contract_text = """
This agreement is between ABC Pvt Ltd and John Doe.
The employee shall not work for a competing firm for 3 years after termination.
The employer may terminate employment without notice.
"""

final_prompt = risk_prompt.format(contract_text=contract_text)

inputs = tokenizer(final_prompt, return_tensors="pt").to(model.device)

with torch.no_grad():
    outputs = model.generate(**inputs, **GENERATION_CONFIG)

print(tokenizer.decode(outputs[0], skip_special_tokens=True))

"""Findings-no labels for clause classification,very generic risk explanation

TASK 2- Contract Summarization
"""

summary_prompt = """
You are a legal assistant. Summarize the following legal contract in simple and clear language.
Highlight key obligations and potential risks.

Contract:
{contract_text}
"""

contract_text = """
This agreement is between ABC Pvt Ltd and John Doe.
The employee shall not work for a competing firm for 3 years after termination.
The employer may terminate employment without notice.
"""

final_prompt = summary_prompt.format(contract_text=contract_text)

inputs = tokenizer(final_prompt, return_tensors="pt").to(model.device)

with torch.no_grad():
    outputs = model.generate(**inputs, **GENERATION_CONFIG)

print(tokenizer.decode(outputs[0], skip_special_tokens=True))

"""Findings-Provides very generic summary with weak risk emphasis and very flat structure

TASK 3-Clause mention
"""

clause_prompt = """
You are a legal assistant. From the following contract, mention the important clauses
that a legal professional should pay attention to.

Contract:
{contract_text}
"""

contract_text = """
This agreement is between ABC Pvt Ltd and ASHWIN.
The employee shall not work for a competing firm for 3 years after termination.
The employer may terminate employment without notice.
"""

final_prompt = clause_prompt.format(contract_text=contract_text)

inputs = tokenizer(final_prompt, return_tensors="pt").to(model.device)

with torch.no_grad():
    outputs = model.generate(**inputs, **GENERATION_CONFIG)

print(tokenizer.decode(outputs[0], skip_special_tokens=True))

"""Findings-Model not adhering to task,inducing hallucination and task drift

Convert to DataFrame
"""

df = pd.DataFrame(results)
df

"""SAVE AND DOWNLOAD BASE GENERAL PURPOSE MODEL OUTPUT"""

df.to_csv("phi2_base_outputs.csv", index=False)

from google.colab import files
files.download("phi2_base_outputs.csv")

"""Phi-2 on LEDGAR"""

!ls -lh LEDGAR_2016-2019_clean.jsonl

"""FINDING THE LEGAL CLAUSE TEXT OF THE LEDGAR DATASET TO EXTRACT"""

import json

with open("LEDGAR_2016-2019_clean.jsonl", "r", encoding="utf-8") as f:
    first_line = json.loads(next(f))

first_line

ledgar_texts.append(item["provision"])

import json

ledgar_texts = []
bad_lines = 0

with open("LEDGAR_2016-2019_clean.jsonl", "r", encoding="utf-8", errors="ignore") as f:
    for line in f:
        try:
            item = json.loads(line)
            if "provision" in item:
                ledgar_texts.append(item["provision"])
        except json.JSONDecodeError:
            bad_lines += 1
            continue

print("Loaded provisions:", len(ledgar_texts))
print("Skipped malformed lines:", bad_lines)

"""LOADING LIMITED NO OF CLAUSES FROM THE DATASET"""

ledgar_texts = ledgar_texts[:10]
len(ledgar_texts)

print(ledgar_texts[0])

"""Run Phi-2 on LEDGAR Provisions"""

from datetime import datetime

for idx, provision_text in enumerate(ledgar_texts):
    contract_id = f"LEDGAR_{idx}"
    timestamp = datetime.now().isoformat()

    # Task 1: Risk Explanation
    risk_output = run_inference(
        risk_prompt.format(contract_text=provision_text),
        model, tokenizer, GENERATION_CONFIG
    )

    # Task 2: Contract Summary
    summary_output = run_inference(
        summary_prompt.format(contract_text=provision_text),
        model, tokenizer, GENERATION_CONFIG
    )

    # Task 3: Clause Mention
    clause_output = run_inference(
        clause_prompt.format(contract_text=provision_text),
        model, tokenizer, GENERATION_CONFIG
    )

    for task, output in [
        ("risk_explanation", risk_output),
        ("contract_summary", summary_output),
        ("clause_mention", clause_output)
    ]:
        results.append({
            "contract_id": contract_id,
            "dataset": "LEDGAR",
            "system": "Base_General_LLM",
            "model": "Phi-2",
            "task": task,
            "output": output,
            "timestamp": timestamp
        })

!pip install -q evaluate rouge_score
import evaluate

rouge = evaluate.load("rouge")

rouge_scores = rouge.compute(
    predictions=[explanation_output],
    references=[REFERENCE_EXPLANATION]
)

print("ROUGE Scores for Explanation:", rouge_scores)

rouge_summary = rouge.compute(
    predictions=[summary_output],
    references=[REFERENCE_SUMMARY]
)

print("ROUGE Scores for Summary:", rouge_summary)