# -*- coding: utf-8 -*-
"""LEGALBART.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZtP_ObO_c33zMK9lsPe24bVyT0_HaFV4
"""

!pip install -q transformers datasets torch scikit-learn pandas

import torch
import random
import numpy as np

SEED = 42
torch.manual_seed(SEED)
np.random.seed(SEED)
random.seed(SEED)

from datasets import load_dataset
from collections import Counter

dataset = load_dataset("lex_glue", "ledgar")
train_data = dataset["train"]

TOP_K = 100

label_counts = Counter(train_data["label"])
valid_labels = sorted([lbl for lbl, _ in label_counts.most_common(TOP_K)])

label_mapping = {lbl: idx for idx, lbl in enumerate(valid_labels)}
reverse_mapping = {idx: lbl for lbl, idx in label_mapping.items()}

label_names = train_data.features["label"].names

import json
import pandas as pd
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report

MODEL_NAME = "nlpaueb/legal-bert-base-uncased"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=2
)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
model.eval()

"""LOAD LEDGAR DATASET"""

from datasets import load_dataset
import pandas as pd
dataset = load_dataset("lex_glue", "ledgar")
df = pd.DataFrame(dataset['train'])
df = df[['text', 'label']]

print(df.head())

"""ENCODE DATASET LABELS"""

label_encoder = LabelEncoder()
df["label_id"] = label_encoder.fit_transform(df["label"])

num_labels = df["label_id"].nunique()
print("Number of classes:", num_labels)

label_counts = df["label"].value_counts()
valid_labels = label_counts[label_counts >= 2].index

df_filtered = df[df["label"].isin(valid_labels)].reset_index(drop=True)

print("Original samples:", len(df))
print("Filtered samples:", len(df_filtered))
print("Remaining classes:", df_filtered["label"].nunique())

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
df_filtered["label_id"] = label_encoder.fit_transform(df_filtered["label"])

"""Split dataset for classification"""

from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(
    df_filtered,
    test_size=0.2,
    stratify=df_filtered["label_id"],
    random_state=42
)

print("Train size:", len(train_df))
print("Test size:", len(test_df))

"""Load LEGALBERT MODEL"""

from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

MODEL_NAME = "nlpaueb/legal-bert-base-uncased"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=df_filtered["label_id"].nunique()
)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

class LegalDataset(torch.utils.data.Dataset):
    def __init__(self, texts, labels):
        self.texts = texts
        self.labels = labels

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        enc = tokenizer(
            self.texts[idx],
            truncation=True,
            padding="max_length",
            max_length=256,
            return_tensors="pt"
        )
        return {
            "input_ids": enc["input_ids"].squeeze(0),
            "attention_mask": enc["attention_mask"].squeeze(0),
            "labels": torch.tensor(self.labels[idx], dtype=torch.long)
        }

train_dataset = LegalDataset(
    train_df["text"].tolist(),
    train_df["label_id"].tolist()
)

test_dataset = LegalDataset(
    test_df["text"].tolist(),
    test_df["label_id"].tolist()
)

from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(
    output_dir="./legalbert_phase2",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=2,
    weight_decay=0.01,
    logging_steps=100,
    report_to="none"
)

"""TRAIN LEGALBERT MODEL"""

from transformers import Trainer, DataCollatorWithPadding
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    data_collator=data_collator,
    processing_class=tokenizer
)

trainer.train()

from sklearn.metrics import classification_report
predictions = trainer.predict(test_dataset)
y_pred = predictions.predictions.argmax(axis=1)
y_true = test_df["label_id"].values

target_names = [str(cls) for cls in label_encoder.classes_]

print(classification_report(
    y_true,
    y_pred,
    target_names=target_names,
    zero_division=0
))

test_df = test_df.reset_index(drop=True)
test_df["predicted_label"] = label_encoder.inverse_transform(y_pred)

test_df.to_csv("legalbert_phase2_predictions.csv", index=False)

errors = test_df[test_df["label"] != test_df["predicted_label"]]
errors.head(10)

model.save_pretrained("centralized_legalbert")
tokenizer.save_pretrained("centralized_legalbert")

!zip -r centralized_legalbert.zip centralized_legalbert

from google.colab import files
files.download("centralized_legalbert.zip")

from transformers import AutoTokenizer, AutoModelForSequenceClassification

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

central_path = "/content/centralized_legalbert"

central_tokenizer = AutoTokenizer.from_pretrained(central_path)
central_model = AutoModelForSequenceClassification.from_pretrained(central_path).to(device)

central_model.eval()

from collections import Counter

# Re-establishing the mapping to ensure it's available for the function
label_counts = Counter(dataset["train"]["label"])
valid_labels = sorted([lbl for lbl, _ in label_counts.most_common(100)])
reverse_mapping = {idx: lbl for idx, lbl in enumerate(valid_labels)}
label_names = dataset["train"].features["label"].names

def phase2_classify(text):
    inputs = central_tokenizer(text, return_tensors="pt", truncation=True).to(device)

    with torch.no_grad():
        outputs = central_model(**inputs)

    predicted_index = torch.argmax(outputs.logits, dim=1).item()

    # Convert predicted index to original label ID, then to readable name
    original_label_id = reverse_mapping[predicted_index]
    clause_name = label_names[original_label_id]

    return clause_name

liability_clause = """
The liability of the Service Provider shall not exceed USD 500,000 in aggregate.
"""

print("PHASE 2 CLASSIFICATION:")
print(phase2_classify(liability_clause))