# -*- coding: utf-8 -*-
"""phase3alegalbert.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FD-ansMzmKVjYq9KEVBsXI0Xo8FgdskD
"""

!pip install -q transformers datasets accelerate scikit-learn

import torch
import copy
import numpy as np
from collections import Counter
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments
)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

dataset = load_dataset("lex_glue", "ledgar")
train_data = dataset["train"].shuffle(seed=42)
print("Total samples:", len(train_data))

TOP_K = 100

label_counts = Counter(train_data["label"])
valid_labels = set(lbl for lbl, _ in label_counts.most_common(TOP_K))

train_data = train_data.filter(lambda x: x["label"] in valid_labels)
print("After filtering:", len(train_data))

label_mapping = {lbl: idx for idx, lbl in enumerate(sorted(valid_labels))}

def remap_labels(example):
    example["label"] = label_mapping[example["label"]]
    return example

train_data = train_data.map(remap_labels)

labels = train_data["label"]
print("Min label:", min(labels))
print("Max label:", max(labels))
print("Unique labels:", len(set(labels)))

"""Tokenization and training split"""

MODEL_NAME = "nlpaueb/legal-bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

def tokenize(batch):
    return tokenizer(
        batch["text"],
        truncation=True,
        padding="max_length",
        max_length=256
    )

train_data = train_data.map(tokenize, batched=True)

train_data.set_format(
    type="torch",
    columns=["input_ids", "attention_mask", "label"]
)

"""Simulate Federated Clients"""

NUM_CLIENTS = 3
client_datasets = np.array_split(train_data, NUM_CLIENTS)

for i, ds in enumerate(client_datasets):
    print(f"Client {i+1} | samples:", len(ds), "| max label:", max([item['label'] for item in ds]))

"""Initialize Global LegalBERT"""

NUM_LABELS = TOP_K

global_model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=NUM_LABELS
).to(device)

"""Local Client Training Function"""

def local_train(global_model, client_dataset, epochs=1):
    local_model = copy.deepcopy(global_model)
    local_model.to(device)

    training_args = TrainingArguments(
        output_dir="./local_output",
        per_device_train_batch_size=8,
        num_train_epochs=epochs,
        logging_steps=50,
        save_strategy="no",
        report_to="none",
        fp16=torch.cuda.is_available()
    )

    trainer = Trainer(
        model=local_model,
        args=training_args,
        train_dataset=client_dataset
    )

    trainer.train()
    return local_model.state_dict(), len(client_dataset)

"""FedAvg Aggregation server side"""

def fedavg(client_weights, client_sizes):
    avg_weights = copy.deepcopy(client_weights[0])
    total = sum(client_sizes)

    for key in avg_weights:
        avg_weights[key] = sum(
            (client_sizes[i] / total) * client_weights[i][key]
            for i in range(len(client_weights))
        )

    return avg_weights

ROUNDS = 3

for r in range(ROUNDS):
    print(f"\nFederated Round {r+1}")

    client_weights = []
    client_sizes = []

    for cid, client_data in enumerate(client_datasets):
        print(f" Client {cid+1} training...")
        weights, size = local_train(global_model, client_data)
        client_weights.append(weights)
        client_sizes.append(size)

    new_global_weights = fedavg(client_weights, client_sizes)
    global_model.load_state_dict(new_global_weights)

print("\nFederated LegalBERT training complete")

global_model.save_pretrained("federated_legalbert")
tokenizer.save_pretrained("federated_legalbert")

!zip -r federated_legalbert.zip federated_legalbert

from google.colab import files
files.download("federated_legalbert.zip")