# -*- coding: utf-8 -*-
"""Phase_3C_Hybrid_Inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rsPNFCSSrdf2l-S-a4LBWSi7HHhKGuK-
"""

!pip install -q transformers peft bitsandbytes accelerate

import torch
import random
import numpy as np

SEED = 42
torch.manual_seed(SEED)
np.random.seed(SEED)
random.seed(SEED)

"""LOAD FEDERATED LEGALBERT"""

from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

legalbert_path = "/content/drive/MyDrive/federated_legalbert"

legal_tokenizer = AutoTokenizer.from_pretrained(legalbert_path)
legal_model = AutoModelForSequenceClassification.from_pretrained(legalbert_path).to(device)

legal_model.eval()

from transformers import AutoModelForCausalLM, BitsAndBytesConfig, AutoConfig, AutoTokenizer

bnb_config = BitsAndBytesConfig(load_in_8bit=True)

model_id = "microsoft/phi-2"
config = AutoConfig.from_pretrained(model_id, trust_remote_code=True)
if not hasattr(config, "pad_token_id"):
    config.pad_token_id = config.eos_token_id

phi_tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)
phi_tokenizer.pad_token = phi_tokenizer.eos_token

phi2_base = AutoModelForCausalLM.from_pretrained(
    model_id,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True,
    config=config
)

GEN_CONFIG = {
    "max_new_tokens": 150,
    "temperature": 0.7,
    "top_p": 0.9,
    "do_sample": True,
    "pad_token_id": phi_tokenizer.eos_token_id,
    "eos_token_id": phi_tokenizer.eos_token_id
}

from datasets import load_dataset
from collections import Counter

dataset = load_dataset("lex_glue", "ledgar")
train_data = dataset["train"]

TOP_K = 100

label_counts = Counter(train_data["label"])
valid_labels = sorted([lbl for lbl, _ in label_counts.most_common(TOP_K)])

label_mapping = {lbl: idx for idx, lbl in enumerate(valid_labels)}
reverse_mapping = {idx: lbl for lbl, idx in label_mapping.items()}

label_names = train_data.features["label"].names

"""LOAD FEDERATED LoRA ADAPTERS"""

from peft import PeftModel

adapter_path = "/content/drive/MyDrive/federated_phi2_adapters"

phi2_model = PeftModel.from_pretrained(phi2_base, adapter_path)

phi2_model.eval()

"""SPRINT 3 STANDARDIZATION"""

def phase3_classify(text):
    inputs = legal_tokenizer(text, return_tensors="pt", truncation=True).to(device)

    with torch.no_grad():
        outputs = legal_model(**inputs)

    predicted_index = torch.argmax(outputs.logits, dim=1).item()

    original_label_id = reverse_mapping[predicted_index]
    clause_name = label_names[original_label_id]

    return clause_name

def phase3_explain(text):
    clause_type = phase3_classify(text)

    prompt = f"""
You are a legal contract analysis assistant.

Analyze the clause below and explain the potential legal risks.

Clause:
{text}

Clause Type: {clause_type}

Provide a short legal risk explanation in 2–3 sentences.
Do not ask questions.
Do not create new tasks.
Only explain the risks of this clause.
"""

    inputs = phi_tokenizer(prompt, return_tensors="pt").to("cuda")

    with torch.no_grad():
        outputs = phi2_model.generate(**inputs, **GEN_CONFIG)

    full_output = phi_tokenizer.decode(outputs[0], skip_special_tokens=True)
    generated_text = full_output[len(prompt):].strip()
    return generated_text
    return full_output

def phase3_summarize(text):
    prompt = f"""
You are a legal contract analysis assistant.

Summarize the following legal clause in ONE sentence.

Clause:
{text}

Summary:
"""

    inputs = phi_tokenizer(prompt, return_tensors="pt").to("cuda")
    summary_config = GEN_CONFIG.copy()
    summary_config["max_new_tokens"] = 40
    with torch.no_grad():
        outputs = phi2_model.generate(**inputs, **summary_config)

    full_output = phi_tokenizer.decode(outputs[0], skip_special_tokens=True)
    generated_text = full_output[len(prompt):].strip()
    stop_words = ["I am a language model", "Exercise", "Use Case", "#"]

    for w in stop_words:
        if w in generated_text:
            generated_text = generated_text.split(w)[0]

    generated_text = generated_text.split("\n")[0]

    return generated_text.strip()

    return generated_text
    return full_output

liability_clause = """
The liability of the Service Provider shall not exceed USD 500,000 in aggregate.
"""

print("PHASE 3 CLASSIFICATION:")
print(phase3_classify(liability_clause))

print("\nPHASE 3 EXPLANATION:")
print(phase3_explain(liability_clause))

print("\nPHASE 3 SUMMARY:")
print(phase3_summarize(liability_clause))

"""ORIGINAL CODING BEFORE CHANGES (ABIJITH)"""

def classify_clause(clause_text):
    inputs = legal_tokenizer(clause_text, return_tensors="pt", truncation=True).to(device)

    with torch.no_grad():
        outputs = legal_model(**inputs)

    predicted_index = torch.argmax(outputs.logits, dim=1).item()

    original_label_id = reverse_mapping[predicted_index]
    clause_name = label_names[original_label_id]

    return clause_name

def generate_explanation(clause_text, clause_label):
    prompt = f"""
Clause:
{clause_text}

Clause Type: {clause_label}

Explain the legal risk clearly in simple terms.

Answer:
"""

    inputs = phi_tokenizer(prompt, return_tensors="pt").to("cuda")

    with torch.no_grad():
        outputs = phi2_model.generate(
            **inputs,
            max_new_tokens=150,
            temperature=0.7
        )

    full_text = phi_tokenizer.decode(outputs[0], skip_special_tokens=True)

    return full_text.split("Answer:")[-1].strip()

def generate_summary(contract_text):
    prompt = f"""
Summarize the following legal contract in simple language:

{contract_text}
Answer:
"""

    inputs = phi_tokenizer(prompt, return_tensors="pt").to("cuda")

    with torch.no_grad():
        outputs = phi2_model.generate(
            **inputs,
            max_new_tokens=100,
            temperature=0.7,
            do_sample=True,
            eos_token_id=phi_tokenizer.eos_token_id,
            pad_token_id=phi_tokenizer.eos_token_id
        )

    full_output = phi_tokenizer.decode(outputs[0], skip_special_tokens=True)

    generated_text = full_output[len(prompt):].strip()
    generated_text = generated_text.split("\n\n")[0]

    return generated_text

def full_contract_review(contract_text):
    clause_label = classify_clause(contract_text)
    explanation = generate_explanation(contract_text, clause_label)
    summary = generate_summary(contract_text)

    return {
        "Clause Type": clause_label,
        "Risk Explanation": explanation,
        "Summary": summary
    }

sample_clause = """
The liability of the provider shall not exceed $10,000 and excludes indirect damages.
"""

result = full_contract_review(sample_clause)

for key, value in result.items():
    print(f"\n{key}:\n{value}")

from datasets import load_dataset
from collections import Counter

dataset = load_dataset("lex_glue", "ledgar")
train_data = dataset["train"]

TOP_K = 100

label_counts = Counter(train_data["label"])
valid_labels = sorted([lbl for lbl, _ in label_counts.most_common(TOP_K)])

label_mapping = {lbl: idx for idx, lbl in enumerate(valid_labels)}
reverse_mapping = {idx: lbl for lbl, idx in label_mapping.items()}