# -*- coding: utf-8 -*-
"""Copy of MODEL_COMPARISON.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lawfMMXglZVUaZULX4bgcu__-FZNA33X
"""

!pip install transformers datasets evaluate peft rouge-score bert-score -q

import torch
import numpy as np
import random

from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    AutoModelForSequenceClassification
)

from peft import PeftModel
from datasets import load_dataset
from collections import Counter

import evaluate
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

"""Reproducibility"""

SEED = 42
torch.manual_seed(SEED)
np.random.seed(SEED)
random.seed(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

"""Generation Config"""

GEN_CONFIG = {
    "max_new_tokens": 150,
    "temperature": 0.7,
    "top_p": 0.9,
    "do_sample": True
}

dataset = load_dataset("lex_glue", "ledgar")

train_data = dataset["train"]
test_data = dataset["test"]

label_names = train_data.features["label"].names

"""Recreate Label Mapping"""

TOP_K = 100

label_counts = Counter(train_data["label"])
valid_labels = sorted([lbl for lbl, _ in label_counts.most_common(TOP_K)])

label_mapping = {lbl: idx for idx, lbl in enumerate(valid_labels)}
reverse_mapping = {idx: lbl for lbl, idx in label_mapping.items()}

"""LOAD BASE DECODDER MODEL"""

from transformers import AutoTokenizer, AutoModelForCausalLM, AutoConfig

phi_tokenizer = AutoTokenizer.from_pretrained("microsoft/phi-2")

if phi_tokenizer.pad_token is None:
    phi_tokenizer.pad_token = phi_tokenizer.eos_token
config = AutoConfig.from_pretrained("microsoft/phi-2")
if not hasattr(config, "pad_token_id") or config.pad_token_id is None:
    config.pad_token_id = phi_tokenizer.pad_token_id

phi2_base = AutoModelForCausalLM.from_pretrained(
    "microsoft/phi-2",
    config=config,
    dtype=torch.float16,
    device_map="auto"
)

"""LOAD CENTRALIZED ENCODER MODEL"""

central_tokenizer = AutoTokenizer.from_pretrained("/content/drive/MyDrive/centralized_legalbert")
central_model = AutoModelForSequenceClassification.from_pretrained(
    "/content/drive/MyDrive/centralized_legalbert"
).to(device)

central_model.eval()

"""Federated LegalBERT"""

fed_tokenizer = AutoTokenizer.from_pretrained("/content/drive/MyDrive/federated_legalbert")

fed_model = AutoModelForSequenceClassification.from_pretrained(
    "/content/drive/MyDrive/federated_legalbert"
).to(device)

fed_model.eval()

pip install --upgrade torchao

phi2_hybrid = PeftModel.from_pretrained(
    phi2_base,
    "/content/drive/MyDrive/federated_phi2_adapters"
)

def classification_prompt(text):
    return f"""
Classify the clause type.

Clause:
{text}

Category:
"""

def explanation_prompt(text):
    return f"""
Explain the legal risks of this clause.

Clause:
{text}

Answer:
"""

def summary_prompt(text):
    return f"""
Summarize this clause in one sentence.

Clause:
{text}

Summary:
"""

def generate_text(prompt):

    inputs = phi_tokenizer(prompt, return_tensors="pt").to("cuda")

    with torch.no_grad():
        outputs = phi2_base.generate(**inputs, **GEN_CONFIG)

    text = phi_tokenizer.decode(outputs[0], skip_special_tokens=True)
    return text[len(prompt):].strip()

"""SPRINT 1 Functions"""

def phase1_classify(text):
    return generate_text(classification_prompt(text))

def phase1_explain(text):
    return generate_text(explanation_prompt(text))

def phase1_summarize(text):
    return generate_text(summary_prompt(text))

"""SPRINT 2 Classification"""

def phase2_classify(text):

    inputs = central_tokenizer(text, return_tensors="pt", truncation=True).to(device)

    with torch.no_grad():
        outputs = central_model(**inputs)

    pred_idx = torch.argmax(outputs.logits, dim=1).item()

    original_label = reverse_mapping.get(pred_idx, pred_idx)

    return label_names[original_label]

"""SPRINT 3 Hybrid Functions"""

def phase3_classify(text):

    inputs = fed_tokenizer(text, return_tensors="pt", truncation=True).to(device)

    with torch.no_grad():
        outputs = fed_model(**inputs)

    pred_idx = torch.argmax(outputs.logits, dim=1).item()

    original_label = reverse_mapping.get(pred_idx, pred_idx)

    return label_names[original_label]

"""EXPLANATION"""

def phase3_explain(text):

    clause_type = phase3_classify(text)

    prompt = f"""
Clause:
{text}

Clause Type: {clause_type}

Explain the legal risk.
"""

    inputs = phi_tokenizer(prompt, return_tensors="pt").to("cuda")

    with torch.no_grad():
        outputs = phi2_hybrid.generate(**inputs, **GEN_CONFIG)

    text = phi_tokenizer.decode(outputs[0], skip_special_tokens=True)

    return text[len(prompt):].strip()

"""SUMMARY"""

def phase3_summarize(text):

    prompt = f"""
Summarize this clause in one sentence.

Clause:
{text}

Summary:
"""

    inputs = phi_tokenizer(prompt, return_tensors="pt").to("cuda")

    summary_config = GEN_CONFIG.copy()
    summary_config["max_new_tokens"] = 40

    with torch.no_grad():
        outputs = phi2_hybrid.generate(**inputs, **summary_config)

    text = phi_tokenizer.decode(outputs[0], skip_special_tokens=True)

    return text[len(prompt):].strip()

"""Classification Evaluation"""

sample_size = 200

texts = []
true_labels = []

for item in test_data.select(range(sample_size)):

    label = item["label"]

    if label in valid_labels:
        texts.append(item["text"])
        true_labels.append(label_names[label])

"""Predictions"""

phase2_preds = []
phase3_preds = []

for t in texts:

    phase2_preds.append(phase2_classify(t))
    phase3_preds.append(phase3_classify(t))

"""Metrics"""

def compute_metrics(true, pred):

    acc = accuracy_score(true, pred)

    precision, recall, f1, _ = precision_recall_fscore_support(
    true, pred, average="macro", zero_division=0
)

    return acc, precision, recall, f1

"""Phase 2 Metrics"""

acc2, prec2, rec2, f12 = compute_metrics(true_labels, phase2_preds)

print("Phase 2 Results")
print("Accuracy:", acc2)
print("Precision:", prec2)
print("Recall:", rec2)
print("F1:", f12)

"""Phase 3 Metrics"""

acc3, prec3, rec3, f13 = compute_metrics(true_labels, phase3_preds)

print("Phase 3 Results")
print("Accuracy:", acc3)
print("Precision:", prec3)
print("Recall:", rec3)
print("F1:", f13)

"""ROUGE Evaluation"""

rouge = evaluate.load("rouge")

clause = """
The liability of the Service Provider shall not exceed USD 500,000.
"""

p1_summary = phase1_summarize(clause)
p3_summary = phase3_summarize(clause)

reference = "The clause limits the provider's liability to USD 500,000."

rouge1 = rouge.compute(predictions=[p1_summary], references=[reference])
rouge3 = rouge.compute(predictions=[p3_summary], references=[reference])

print("Phase1 ROUGE:", rouge1)
print("Phase3 ROUGE:", rouge3)

"""Example Hybrid Output"""

clause = """
The liability of the Service Provider shall not exceed USD 500,000 in aggregate.
"""

print("Phase1 Explanation:")
print(phase1_explain(clause))

print("\nPhase3 Explanation:")
print(phase3_explain(clause))

"""VIZUALIZATION"""

!pip install matplotlib seaborn pandas -q

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

sns.set_style("whitegrid")

"""INPUT METRICS FROM ABOVE"""

phase2_results = {
    "Accuracy": 0.88,
    "Precision": 0.7895,
    "Recall": 0.8224,
    "F1": 0.7855
}

phase3_results = {
    "Accuracy": 0.85,
    "Precision": 0.7406,
    "Recall": 0.7581,
    "F1": 0.7287
}

phase1_rouge = {
    "ROUGE-1": 0.545,
    "ROUGE-2": 0.300,
    "ROUGE-L": 0.545
}

phase3_rouge = {
    "ROUGE-1": 0.571,
    "ROUGE-2": 0.316,
    "ROUGE-L": 0.571
}

"""CLASSIFICATION METRICS"""

classification_table = pd.DataFrame({
    "Metric": ["Accuracy", "Precision", "Recall", "F1 Score"],
    "Centralized LegalBERT (Phase 2)": list(phase2_results.values()),
    "Federated Hybrid Model (Phase 3)": list(phase3_results.values())
})

classification_table

import matplotlib.pyplot as plt
import numpy as np

metrics = ["Accuracy", "Precision", "Recall", "F1 Score"]

phase2 = [0.88,0.7895,0.8224,0.7855]
phase3 = [0.85,0.7406,0.7581,0.7287]

x = np.arange(len(metrics))
width = 0.35

plt.figure(figsize=(8,5))

plt.bar(x - width/2, phase2, width, label="LegalBERT")
plt.bar(x + width/2, phase3, width, label="Hybrid")

plt.xticks(x, metrics)
plt.ylabel("Score")
plt.title("Classification Performance Comparison")
plt.ylim(0,1)
plt.legend()

plt.savefig("classification_bar_chart.png",dpi=300,bbox_inches="tight")

plt.show()

df = pd.DataFrame({
    "Metric": ["Accuracy", "Precision", "Recall", "F1"],
    "(Centralized)": list(phase2_results.values()),
    "(Federated Hybrid)": list(phase3_results.values())
})

df.set_index("Metric").plot(kind="bar", figsize=(8,5))

plt.title("Classification Performance Comparison")
plt.ylabel("Score")
plt.xticks(rotation=0)
plt.legend()
plt.ylim(0,1)
plt.show()

tasks = ["Accuracy","Precision","Recall","F1"]

phase2 = np.array([0.88,0.7895,0.8224,0.7855])
phase3 = np.array([0.85,0.7406,0.7581,0.7287])

plt.figure(figsize=(8,5))

plt.bar(tasks, phase2, label="LegalBERT")
plt.bar(tasks, phase3, bottom=phase2, label="Hybrid")

plt.title("Stacked Performance Comparison")
plt.ylabel("Score")

plt.legend()

plt.savefig("stacked_performance_chart.png",dpi=300,bbox_inches="tight")

plt.show()

import seaborn as sns

heat_data = [
    [0.88,0.7895,0.8224,0.7855],
    [0.85,0.7406,0.7581,0.7287]
]

labels=["Accuracy","Precision","Recall","F1"]

plt.figure(figsize=(8,4))

sns.heatmap(heat_data,
            annot=True,
            xticklabels=labels,
            yticklabels=["LegalBERT","Hybrid"],
            cmap="YlGnBu")

plt.title("Performance Metrics Comparison")

plt.savefig("metrics_heatmap.png",dpi=300,bbox_inches="tight")

plt.show()

"""training time-tbd"""

models=["Centralized LegalBERT","Federated LegalBERT","Hybrid Federated System",]

training_time=[83,44.8,47.3]
plt.figure(figsize=(6,4))

plt.plot(models,training_time,marker="o")

plt.ylabel("Training Time (Minutes)")
plt.title("Training Time Comparison")
plt.ylim(0, 100)

for i, time in enumerate(training_time):
    plt.text(i, time + 2, str(time), ha='center', va='bottom')

plt.show()

"""SUMMARY PERFORMANCE"""

rouge_table = pd.DataFrame({
    "Metric": ["ROUGE-1", "ROUGE-2", "ROUGE-L"],
    "Base Phi-2 (Phase 1)": list(phase1_rouge.values()),
    "Hybrid Federated Model (Phase 3)": list(phase3_rouge.values())
})

rouge_table

rouge_df = pd.DataFrame({
    "Metric": ["ROUGE-1", "ROUGE-2", "ROUGE-L"],
    "(Base Phi-2)": list(phase1_rouge.values()),
    "(Hybrid Model)": list(phase3_rouge.values())
})

rouge_df.set_index("Metric").plot(kind="bar", figsize=(8,5))

plt.title("Summarization Quality (ROUGE Scores)")
plt.ylabel("Score")
plt.ylim(0,0.6)
plt.xticks(rotation=0)
plt.show()

"""OVERALL PERFORMANCE"""

overall_table = pd.DataFrame({
    "Model": [
        "Base Phi-2 (General LLM)",
        "Centralized LegalBERT",
        "Federated Hybrid Model"
    ],
    "Clause Classification": [
        "Prompt-based",
        "Supervised",
        "Federated + Supervised"
    ],
    "Classification F1": [
        "N/A",
        0.7855,
        0.7287
    ],
    "ROUGE-1": [
        0.545,
        "N/A",
        0.571
    ],
    "Privacy Preserving": [
        "No",
        "No",
        "Yes"
    ]
})

overall_table

comparison = pd.DataFrame({
    "Model": ["Base Phi-2", "Centralized LegalBERT", "Federated Hybrid"],
    "Classification F1": [0, 0.7855, 0.7287],
    "ROUGE-1": [0.545, 0, 0.571]
})

comparison.set_index("Model").plot(kind="bar", figsize=(8,5))

plt.title("Overall Model Performance Comparison")
plt.ylabel("Score")
plt.xticks(rotation=0)
plt.show()

labels = ["Accuracy", "Precision", "Recall", "F1"]

phase2_values = list(phase2_results.values())
phase3_values = list(phase3_results.values())

angles = np.linspace(0, 2*np.pi, len(labels), endpoint=False)

phase2_values += phase2_values[:1]
phase3_values += phase3_values[:1]
angles = np.concatenate((angles, [angles[0]]))

fig = plt.figure(figsize=(6,6))
ax = plt.subplot(111, polar=True)

ax.plot(angles, phase2_values, label="Centralized LegalBERT")
ax.fill(angles, phase2_values, alpha=0.1)

ax.plot(angles, phase3_values, label="Federated Hybrid")
ax.fill(angles, phase3_values, alpha=0.1)

ax.set_thetagrids(angles[:-1]*180/np.pi, labels)

plt.title("Classification Performance Radar Chart")
plt.legend()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

labels = ["ROUGE-1", "ROUGE-2", "ROUGE-L"]

phase1_values = [
    phase1_rouge["ROUGE-1"],
    phase1_rouge["ROUGE-2"],
    phase1_rouge["ROUGE-L"]
]

phase3_values = [
    phase3_rouge["ROUGE-1"],
    phase3_rouge["ROUGE-2"],
    phase3_rouge["ROUGE-L"]
]
angles = np.linspace(0, 2*np.pi, len(labels), endpoint=False)

phase1_values += phase1_values[:1]
phase3_values += phase3_values[:1]
angles = np.concatenate((angles, [angles[0]]))

fig = plt.figure(figsize=(6,6))
ax = plt.subplot(111, polar=True)

ax.plot(angles, phase1_values, label="Base Phi-2", linewidth=2)
ax.fill(angles, phase1_values, alpha=0.15)

ax.plot(angles, phase3_values, label="Hybrid Federated", linewidth=2)
ax.fill(angles, phase3_values, alpha=0.15)

ax.set_thetagrids(angles[:-1]*180/np.pi, labels)

plt.title("ROUGE Score Comparison (Radar Chart)", fontsize=12)
plt.legend(loc="upper right")

plt.show()