# -*- coding: utf-8 -*-
"""Phase_3B_Federated_Phi2_PEFT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10DMu9uiuNGUhWVBatFww95h2aKJqb8-2
"""

!pip install -q transformers peft accelerate datasets bitsandbytes

import torch
import copy
import numpy as np
from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, TrainingArguments, Trainer
from peft import LoraConfig, get_peft_model

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

"""Load Phi-2"""

MODEL_NAME = "microsoft/phi-2"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token
from transformers import AutoConfig
config = AutoConfig.from_pretrained(MODEL_NAME, trust_remote_code=True)
config.pad_token_id = tokenizer.pad_token_id

base_model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    config=config,
    torch_dtype=torch.float16,
    device_map="auto",
    trust_remote_code=True
)

base_model.requires_grad_(False)

"""Attach LoRA Adapters"""

lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    target_modules=["q_proj", "k_proj", "v_proj", "dense"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

global_model = get_peft_model(base_model, lora_config)
global_model.print_trainable_parameters()

def build_prompt(clause):
    return f"""
Explain the legal risk in simple terms:

Clause:
{clause}

Explanation:
"""

clauses = [
    "The liability of the provider shall not exceed $10,000.",
    "Either party may terminate this agreement with 30 days notice.",
    "This agreement shall be governed by the laws of California.",
    "The company is not responsible for indirect damages."
]

data = [{"text": build_prompt(c)} for c in clauses * 50]
dataset = Dataset.from_list(data)

"""Tokenization"""

def tokenize(batch):
    tokens = tokenizer(
        batch["text"],
        truncation=True,
        padding="max_length",
        max_length=256
    )
    tokens["labels"] = tokens["input_ids"].copy()
    return tokens

dataset = dataset.map(tokenize, batched=True)
dataset.set_format(
    type="torch",
    columns=["input_ids", "attention_mask", "labels"]
)

"""Simulate Federated Clients"""

NUM_CLIENTS = 3
client_datasets = np.array_split(dataset, NUM_CLIENTS)

for i, ds in enumerate(client_datasets):
    print(f"Client {i+1} samples:", len(ds))

"""Local Client Training of ADAPTERS ONLY"""

import gc

def local_train_phi(global_model, client_dataset, epochs=1):
    global_model.train()

    args = TrainingArguments(
        output_dir="./phi_local",
        per_device_train_batch_size=1,
        gradient_accumulation_steps=8,
        num_train_epochs=epochs,
        fp16=True,
        save_strategy="no",
        logging_steps=20,
        report_to="none"
    )

    trainer = Trainer(
        model=global_model,
        args=args,
        train_dataset=client_dataset
    )

    trainer.train()

    # Extract ONLY LoRA adapter weights
    adapter_weights = {
        k: v.detach().cpu()
        for k, v in global_model.state_dict().items()
        if "lora" in k
    }

    # 🔥 CRITICAL MEMORY CLEANUP
    del trainer
    torch.cuda.empty_cache()
    gc.collect()

    return adapter_weights, len(client_dataset)

"""FedAvg for Adapter Weights"""

def fedavg(client_weights, client_sizes):
    avg_weights = copy.deepcopy(client_weights[0])
    total = sum(client_sizes)

    for key in avg_weights:
        avg_weights[key] = sum(
            (client_sizes[i] / total) * client_weights[i][key]
            for i in range(len(client_weights))
        )
    return avg_weights

ROUNDS = 3

for r in range(ROUNDS):
    print(f"\nFederated Phi-2 Round {r+1}")

    client_weights = []
    client_sizes = []

    for cid, client_data in enumerate(client_datasets):
      print(f" Client {cid+1} training adapters...")
      weights, size = local_train_phi(global_model, client_data)

      client_weights.append(weights)
      client_sizes.append(size)

    # Reset gradients before next client
      global_model.zero_grad(set_to_none=True)


    import torch
    torch.cuda.empty_cache()

    new_weights = fedavg(client_weights, client_sizes)
    global_model.load_state_dict(new_weights, strict=False)

print("\nFederated Phi-2 adapter training complete")

global_model.save_pretrained("federated_phi2_adapters")
tokenizer.save_pretrained("federated_phi2_adapters")

!zip -r federated_phi2_adapters.zip federated_phi2_adapters

from google.colab import files
files.download("federated_phi2_adapters.zip")